version: "3.8"
services:
  csserver:
    command:
      - "-game"
      - "cstrike"
      - "+maxplayers"
      - "12"
      - "+map"
      - "de_dust2"
      - "+sv_lan"
      - "0"
      - "+ip"
      - "0.0.0.0"
      - "+port"
      - "27015"
      - "+sys_ticrate"
      - "1000"
      - "+fps_max"
      - "1000"
      - "-pingboost"
      - "3"
      - "-nomaster"
      - "-strictportbind"
    environment:
      MAXPLAYERS: "12"
      MAP: "de_dust2"
